---
title: Your awesome title
timezone: Europe/Paris
collections:
  authors:
    title: Authors
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: authors
  values:
    layout: author
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author: ted
    featured_file: 
- scope:
    path: ''
  values:
    layout: default
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: 
twitter_username: jekyllrb
github_username: jekyll
theme: 
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-paginate
paginate: 2
feed:
  posts_limit: 500
paginate_path: "/blog/page:num/"
repository: atomas18/hello-world
